[project]
name = "fx-nono"
version = "1.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "coverage>=7.12.0",
    "jsonpickle>=4.1.1",
    "pygame>=2.6.1",
]
